# Generated by Django 5.1.6 on 2025-04-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(default='', max_length=90)),
                ('address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
