# Generated by Django 5.1.6 on 2025-04-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customerdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='user',
        ),
    ]
