# Generated by Django 5.1.6 on 2025-02-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='product_name',
        ),
    ]
