# Generated by Django 5.1.4 on 2025-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('city', models.TextField(max_length=90)),
                ('state', models.TextField(max_length=100)),
                ('zip_code', models.TextField(max_length=20)),
            ],
        ),
    ]
