# Generated by Django 5.1.4 on 2025-03-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_shop', '0007_orderupdate_alter_orders_address_alter_orders_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
