# Generated by Django 5.1.6 on 2025-03-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_shop', '0008_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='small_desc',
        ),
    ]
