# Generated by Django 5.1.6 on 2025-04-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_shop', '0011_product_weight_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='small_desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
