# Generated by Django 5.1.6 on 2025-04-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_shop', '0014_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
    ]
