services:
  - name: ananta-devgad-hapus
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn Ananta_Devgad_Hapus.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "devgad-alphanso.onrender.com"
    static:
      - name: media
        path: /media
        source: media
      - name: static
        path: /static
        source: staticfiles
